"""[SP001] Init models

Revision ID: 1c286dd689e5
Revises:
Create Date: 2026-02-23 22:59:50.470867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c286dd689e5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("PENDING", "QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELED", "RETRYING", name="task_status").create(
        op.get_bind()
    )
    sa.Enum("SCRIPT", "AGENT_GRPC", "AGENT_HTTP", "DIRECT", name="execution_method").create(op.get_bind())
    sa.Enum("ONE_TIME", "RECURRING", "SCHEDULED", name="task_type").create(op.get_bind())
    sa.Enum("ONLINE", "OFFLINE", "BUSY", "ERROR", name="agent_status").create(op.get_bind())
    sa.Enum("GRPC", "HTTP", name="agent_connection_type").create(op.get_bind())
    op.create_table(
        "agent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=True),
        sa.Column(
            "connection_type",
            postgresql.ENUM("GRPC", "HTTP", name="agent_connection_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("ONLINE", "OFFLINE", "BUSY", "ERROR", name="agent_status", create_type=False),
            nullable=False,
        ),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_tasks", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_tasks", sa.Integer(), nullable=False),
        sa.Column("total_tasks_completed", sa.Integer(), nullable=False),
        sa.Column("total_tasks_failed", sa.Integer(), nullable=False),
        sa.Column("avg_response_time_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_user", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_agent_id"), "agent", ["id"], unique=False)
    op.create_index(op.f("ix_agent_last_heartbeat"), "agent", ["last_heartbeat"], unique=False)
    op.create_index(op.f("ix_agent_status"), "agent", ["status"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_type",
            postgresql.ENUM("ONE_TIME", "RECURRING", "SCHEDULED", name="task_type", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "execution_method",
            postgresql.ENUM("SCRIPT", "AGENT_GRPC", "AGENT_HTTP", "DIRECT", name="execution_method", create_type=False),
            nullable=False,
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schedule_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                "RETRYING",
                name="task_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_delay", sa.Integer(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_trace", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_user", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_next_run", "task", ["next_run_at"], unique=False, postgresql_where=sa.text("task_type != 'ONE_TIME'")
    )
    op.create_index("idx_task_user_status", "task", ["user_id", "status"], unique=False)
    op.create_index(op.f("ix_task_id"), "task", ["id"], unique=False)
    op.create_index(op.f("ix_task_priority"), "task", ["priority"], unique=False)
    op.create_index(op.f("ix_task_status"), "task", ["status"], unique=False)
    op.create_index(op.f("ix_task_task_type"), "task", ["task_type"], unique=False)
    op.create_index(op.f("ix_task_user_id"), "task", ["user_id"], unique=False)
    op.create_table(
        "task_execution",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "execution_method",
            postgresql.ENUM("SCRIPT", "AGENT_GRPC", "AGENT_HTTP", "DIRECT", name="execution_method", create_type=False),
            nullable=False,
        ),
        sa.Column("agent_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELED",
                "RETRYING",
                name="task_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=True),
        sa.Column("stderr", sa.Text(), nullable=True),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("bytes_transferred", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_user", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_execution_id"), "task_execution", ["id"], unique=False)
    op.create_index(op.f("ix_task_execution_task_id"), "task_execution", ["task_id"], unique=False)
    op.create_table(
        "task_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("component", sa.String(length=50), nullable=True),
        sa.Column("metadata_val", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_user", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["task_execution.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_log_level_time", "task_log", ["level", "timestamp"], unique=False)
    op.create_index("idx_log_task_time", "task_log", ["task_id", "timestamp"], unique=False)
    op.create_index(op.f("ix_task_log_execution_id"), "task_log", ["execution_id"], unique=False)
    op.create_index(op.f("ix_task_log_id"), "task_log", ["id"], unique=False)
    op.create_index(op.f("ix_task_log_task_id"), "task_log", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_log_timestamp"), "task_log", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_log_timestamp"), table_name="task_log")
    op.drop_index(op.f("ix_task_log_task_id"), table_name="task_log")
    op.drop_index(op.f("ix_task_log_id"), table_name="task_log")
    op.drop_index(op.f("ix_task_log_execution_id"), table_name="task_log")
    op.drop_index("idx_log_task_time", table_name="task_log")
    op.drop_index("idx_log_level_time", table_name="task_log")
    op.drop_table("task_log")
    op.drop_index(op.f("ix_task_execution_task_id"), table_name="task_execution")
    op.drop_index(op.f("ix_task_execution_id"), table_name="task_execution")
    op.drop_table("task_execution")
    op.drop_index(op.f("ix_task_user_id"), table_name="task")
    op.drop_index(op.f("ix_task_task_type"), table_name="task")
    op.drop_index(op.f("ix_task_status"), table_name="task")
    op.drop_index(op.f("ix_task_priority"), table_name="task")
    op.drop_index(op.f("ix_task_id"), table_name="task")
    op.drop_index("idx_task_user_status", table_name="task")
    op.drop_index("idx_task_next_run", table_name="task", postgresql_where=sa.text("task_type != 'ONE_TIME'"))
    op.drop_table("task")
    op.drop_index(op.f("ix_agent_status"), table_name="agent")
    op.drop_index(op.f("ix_agent_last_heartbeat"), table_name="agent")
    op.drop_index(op.f("ix_agent_id"), table_name="agent")
    op.drop_table("agent")
    sa.Enum("GRPC", "HTTP", name="agent_connection_type").drop(op.get_bind())
    sa.Enum("ONLINE", "OFFLINE", "BUSY", "ERROR", name="agent_status").drop(op.get_bind())
    sa.Enum("ONE_TIME", "RECURRING", "SCHEDULED", name="task_type").drop(op.get_bind())
    sa.Enum("SCRIPT", "AGENT_GRPC", "AGENT_HTTP", "DIRECT", name="execution_method").drop(op.get_bind())
    sa.Enum("PENDING", "QUEUED", "RUNNING", "COMPLETED", "FAILED", "CANCELED", "RETRYING", name="task_status").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
